server.port=8080
spring.application.name=account-service
spring.profiles.active=dev

spring.cloud.nacos.config.server-addr=18.181.159.177:8848
spring.cloud.nacos.discovery.server-addr=18.181.159.177:8848

spring.config.import=nacos:account-service-dev.properties?group=DEFAULT_GROUP&refreshEnabled=true
